version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--databases", "16"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - SERVICE_TYPE=main
      - PNL_ENABLED=false
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./tmp/sessions/user:/app/src/tmp/sessions/user
    command: ["npm", "run", "run:listener"]
    restart: unless-stopped
    networks:
      - app-network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - RUN_CONSUMER=true
      - SERVICE_TYPE=main
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["node", "src/consumer"]
    restart: unless-stopped
    networks:
      - app-network

  pnl-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - SERVICE_TYPE=pnl
      - PNL_ENABLED=true
      - PNL_TELEGRAM_API_ID=${PNL_TELEGRAM_API_ID:-${TELEGRAM_API_ID}}
      - PNL_TELEGRAM_API_HASH=${PNL_TELEGRAM_API_HASH:-${TELEGRAM_API_HASH}}
    volumes:
      - ./:/app
      - /app/node_modules
      - ./tmp/sessions/pnl_bot:/app/src/tmp/sessions/pnl_bot
      - ./src/config:/app/src/config
    command: ["node", "src/pnlBot.js"]
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge