services:
  #############################
  # Shared infrastructure
  #############################
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  #############################
  # Main App Services
  #############################
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - SERVICE_TYPE=main   
      - PNL_ENABLED=false
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "run:listener"]
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      app:
        condition: service_started
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - RUN_CONSUMER=true
      - SERVICE_TYPE=main
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["node", "src/consumer"]
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 384M

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local