version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    # ...other redis config if needed...
  
  redis-init:
    image: redis:alpine
    depends_on:
      - redis
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_SESSION_STRING: ${TELEGRAM_SESSION_STRING}
      AI_PROVIDER: ${AI_PROVIDER}
      AI_API_KEY: ${AI_API_KEY}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      MESSAGE_QUEUE_NAME: ${MESSAGE_QUEUE_NAME}
      MAX_QUEUE_RETRIES: ${MAX_QUEUE_RETRIES}
      MESSAGE_PROCESS_TIMEOUT: ${MESSAGE_PROCESS_TIMEOUT}
    volumes:
      - ./redis-init.sh:/redis-init.sh
    command: ["sh", "/redis-init.sh"]
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - redis-init
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["npm", "run", "run:listener"]
# ...other services if needed...
