version: '3'

services:
  pnl-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - PNL_ENABLED=true
      - USE_SEPARATE_CLIENT=true
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "run:pnl"]
    restart: unless-stopped
    networks:
      - backend_default

  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - backend_default

networks:
  backend_default:
    external: true